Vagrant.configure("2") do |config|

    # create okd1 node
    config.vm.define :okd1 do |okd1_config|
      okd1_config.vm.box = "centos/7"
      okd1_config.vm.network "bridged"
      okd1_config.vm.hostname = "okd1.ycube.local"
      okd1_config.vm.provider "virtualbox" do |vb|
        vb.memory = "4096"
      end
      okd1_config.vm.network "forwarded_port", guest: 8443, host: 8443
      okd1_config.vm.network :forwarded_port, guest: 80, host: 80
      okd1_config.vm.network :forwarded_port, guest: 443, host: 443
    end 
    
    
    # create okd2 node
    config.vm.define :okd2 do |okd2_config|
      okd2_config.vm.box = "centos/7"
      okd2_config.vm.hostname = "okd2.ycube.local"     
      okd2_config.vm.provider "virtualbox" do |vb|
        vb.memory = "3072"
      end
    end 
   
   # Create mysql
  config.vm.define :mysql do |mysql_config|
        mysql_config.vm.box = "ubuntu/xenial64"
        mysql_config.vm.network "forwarded_port", guest: 3306, host: 3306
        mysql_config.vm.provision :shell, path: "bootstrap.sh"
  end

    
end

###################################

config.vm.define "activemq" do |activemq|
    activemq.vm.box = "ubuntu/trusty32"
    activemq.vm.network :forwarded_port, guest: 8161, host: 8161, auto_correct: true
    activemq.vm.network :forwarded_port, guest: 6166, host: 6166, auto_correct: true
    activemq.vm.network :forwarded_port, guest: 6163, host: 6163, auto_correct: true
  end

config.vm.provision :shell, inline: <<-SHELL
    cd /home/vagrant/ && wget https://archive.apache.org/dist/activemq/5.14.1/apache-activemq-5.14.1-bin.tar.gz
    cd /home/vagrant/ && tar -zxvf apache-activemq-5.14.1-bin.tar.gz
    cd /home/vagrant/apache-activemq-5.14.1/bin && chmod 755 activemq
    sudo apt-get update
    sudo apt-get install default-jdk -y
    echo 'JAVA_HOME="/usr/lib/jvm/java-7-openjdk-i386/"' | sudo tee -a /etc/environment
    source /etc/environment
    cd /home/vagrant/apache-activemq-5.14.1/bin && sudo sh activemq start
  SHELL

config.vm.provision :shell, :inline => "cd /home/vagrant/apache-activemq-5.14.1/bin && sudo sh activemq start", run: "always"
